apiVersion: v1
kind: Service
metadata:
  name: apiproject
  labels:
    app: apiproject
spec:
  type: NodePort
  selector:
    app: apiproject
  ports:
    - port: 8080          # port other in-cluster services would use
      targetPort: 8080    # port the container listens on
      nodePort: 30080      # port you'll hit on localhost (30000-32767 range)
